### PR TITLE
Project cards

### PR DESCRIPTION
**Pull request by Priyal-Saxena**

### CODE REVIEW

**Comment by AlacritousCreature** [comment]
Your commit-


expected cards :






@Priyal-Saxena kindly go through the issue heading and description once again and do the necessary changes:

1) there should 2 cards in a row with the proper spacing as in design.
2) the buttons aren't same as in the design
3)there is no hover effect as in design.
4) the project name should be quite close to the logo, see in design
5) Also insert a dummy logo in the image and change the font of cards as in the design, notice wherever its bold or not.

**Comment by AlacritousCreature** [comment]
@stygian-96 @hardikbajaj

**Comment by Priyal-Saxena** [comment]
Sorry, I had not scrolled to the figma design of admin part so I missed that, and other details as well, though I have implemented them now, this is how it looks - 
image
Also I have wrapped the button component in Link tag, so it should be easy to connect to the backend, as well as gives the freedom to use features of Button tag.

**Comment by AlacritousCreature** [comment]
@Priyal-Saxena  the cards now looks good, but please change the button color same as in design.....if u don't know which it is ask to manav, and also the github button's outline is quite dark. And it doesn't need this border of just one grey line. it just need a slight shadow of grey color....see in the design , it is mentioned on the top

**Comment by AlacritousCreature** [comment]
https://www.figma.com/file/dQiafLT36S5FTQhEuxvUFU/GDSC-Web-UI?node-id=0%3A1

**Comment by Priyal-Saxena** [comment]
cards now
image
image
also for the event cards, there is a boolean prop called "upcoming", if the value is true then the RSVP button is displayed, else it's not displayed.

**Comment by AlacritousCreature** [comment]
@Priyal-Saxena  @shlesh both the are good, just one thing left is that there is rounded cut below the image and above the event name in project card. I had tried by putting another image.....see the ss attached above for it.

**Comment by shlesh** [comment]
on it maam!
we'll make a pr soon

**Comment by Priyal-Saxena** [comment]
@AlacritousCreature 
this is how it looks now
image

**Pull request merged**
