### PR TITLE
Added Technology Cards

### PR DESCRIPTION
**Pull request by shlesh**

### CODE REVIEW

**Comment by AlacritousCreature** [comment]
@shlesh do the required and informed changes  fast! After some much time you were expected to come up with good cards and with some animative feature.

**Comment by shlesh** [comment]
> @shlesh do the required and informed changes fast! After some much time you were expected to come up with good cards and with some animative feature.

Will do maam!
sorry we have a test right now, Ill start working on it as soon as this is over

**Comment by AlacritousCreature** [comment]
okay

**Comment by shlesh** [comment]
maam i'll make another PR

**Pull request closed without merging**
