### PR TITLE
Changed carousel and events page cards

### PR DESCRIPTION
**Pull request by shlesh**

### CODE REVIEW

**Comment by shlesh** [comment]
image

**Comment by shlesh** [comment]
image
@hardikbajaj sir the carousel info section on the left needs styling

**Comment by shlesh** [comment]
The carousel section still needs some minor styling

**Comment by AlacritousCreature** [comment]
The carousel is too good in mobile view too, and events cards are also of same height now, but.....


1)carousel is creating the x axis scrolling bar and a white verticals section on right
2)the section for submit events speaker proposal got distorted
3) The footer section too got distorted in mobile view

**Comment by shlesh** [comment]
>   
> 
> The carousel is too good in mobile view too, and events cards are also of same height now, but.....
> 
> 1)carousel is creating the x axis scrolling bar and a white verticals section on right 2)the section for submit events speaker proposal got distorted 3) The footer section too got distorted in mobile view

Right maam ill look into it asap

**Comment by shlesh** [comment]
@AlacritousCreature maam could you please review this PR

**Comment by AlacritousCreature** [comment]
1)events cards aren't starting from flex-start yet. we want the alignment of these cards as blogs cards, like all the cards start from same y coordinate and even if anyone of one row have large height, the next row will start from y-coordinate below than upper large card
2)intrested in speaking"" section's alignment isn't still like the projects page's similar section in mobile view
3)the bg of carousel is great coz of its parallax effect, but it isn't something related to our theme, so remove the background of carousel, we need to put the same gradient as in last carousel.

**Comment by shlesh** [comment]
image
@AlacritousCreature maam ive checked on multiple browsers but the cards seem fine for me

**Comment by hardikbajaj** [comment]
@AlacritousCreature merging this pr, will open other issue branch for further fixes

**Pull request merged**
