### PR TITLE
edited project cards

### PR DESCRIPTION
**Pull request by Priyal-Saxena**

### CODE REVIEW

**Comment by AlacritousCreature** [comment]
@Priyal-Saxena the cards are perfect or even too good for this website....just one that that u might have forgot to put edit and delete buttons. insert it to the right of 'github' and 'view project buttons'

**Comment by Priyal-Saxena** [comment]
Thank you mam.
mam they are there, but by default they are hidden. The "admin" state can
be set to true to make them visible.
[image: image.png]
should I place them to the right?

**Comment by AlacritousCreature** [comment]
can you put a screenshot of it, like how it looks currently?

**Comment by Priyal-Saxena** [comment]
image
sorry my bad, the pic never uploaded :(

**Comment by AlacritousCreature** [comment]
Yeah its visible now.....great!!

**Comment by Priyal-Saxena** [comment]
thank you mam

**Pull request merged**
