### PR TITLE
added "+" button etc

### PR DESCRIPTION
**Pull request by Priyal-Saxena**

### CODE REVIEW

**Comment by AlacritousCreature** [comment]
can you once see for this error?

**Comment by Priyal-Saxena** [comment]
> 
> 
> can you once see for this error?

 try "npm install @mui/icons-material" command in terminal.

**Comment by AlacritousCreature** [comment]
@Priyal-Saxena I have checked it by installing it, but put this in package.json file as everyone will be using it. Also the headings are good, but on the normal laptop screen it was supposed to be at the left corner only as it was earlier on blogs page.....just the change was that when we see it from smaller screens, it should come to the center(mobile responsiveness). Align those headings to the left side as it was in blogs page before, for all the pages, including the about page.

**Comment by AlacritousCreature** [comment]
@Priyal-Saxena updates?

**Comment by Priyal-Saxena** [comment]
mam I have completed the required changes, and added "@mui/icons-material" as a dependancy, if there are any more dependencies please let me know, and I'll add them as well. (as there might be some package that I used but forgot to add as a dependancy.)
This is what the current website looks like:
image
image

**Comment by AlacritousCreature** [comment]
@Priyal-Saxena sorry i wasn't home yestarday.

**Comment by AlacritousCreature** [comment]
everything seems to be good!

**Pull request merged**
